default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "ec2-user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "your_database_password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: pawpals_db_development

test:
  <<: *default
  database: pawpals_db_test

production:
  <<: *default
  database: pawpals_db_production
  username: <%= ENV.fetch("DB_USERNAME", "ec2-user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "your_database_password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
